### ISSUE TITLE
Souce code and model request

### ISSUE THREAD

**Issue by aukhanee** [AlexOlsen/DeepWeeds#1]
I read your research paper and downloaded your images. It's a great effort compared to other available datasets. Could you please share some source code and model to replicate your results presented in the paper? I need it for a class project and it would be a huge task if I were to build the system for basic frameworks. Thanks.

**Comment by AlexOlsen** [comment]
Hi au1khan, thanks for your compliments and interest in our research! Our paper is currently under peer review. I'll be sharing our complete source code, allowing full replication of our results, once we have a decision from the peer review process and the paper is accepted for publication. This will hopefully happen in the coming weeks.

**Comment by AlexOlsen** [comment]
Hi au1khan, our paper has been published by Scientific Reports and I have added my entire source code to the repo. Best of luck!
