### ISSUE TITLE
No labels in the images.zip

### ISSUE THREAD

**Issue by hbzhang** [AlexOlsen/DeepWeeds#11]
There, I am interested in working on the data. Thanks for your work.

However, I can not find the labels in the images.zip. 

There are no folders in the unzip folder. All images are just in one single folder.

Thanks

**Comment by AlexOlsen** [comment]
Hi @hbzhang.. The labels are [in the repository](https://github.com/AlexOlsen/DeepWeeds/tree/master/labels).
